# EDA

In [1]:
import json
import pandas as pd

with open("../data/raw_ads_2511.json", encoding="utf-8") as f:
    df = pd.DataFrame(json.load(f))

In [2]:
df.head()

,id,version_id,title,employer,municipality,region,occupation,published,deadline,description
0,29427644,0a8a4a1038a8146a044682a6c77b69076a0c689d,Domänarkitekt,Säkerhetspolisen,Stockholm,Stockholms län,Systemanalytiker/Systemutredare,2025-01-31T09:54:18,2025-04-14T23:59:59,Vill du driva teknisk förändring i en av de vi...
1,29403435,646b1b1099909ef1d5cb13571309ea9da0986b2e,Industriell verksamhetsutvecklare inom IT och ...,Jobnet AB,Göteborg,Västra Götalands län,"Affärskonsult, IT",2025-01-22T17:38:54,2025-03-12T23:59:59,"Bli en del av Prevas, ett innovativt företag i..."
2,29403435,969cc4bc28a2090b1bb17611052aaddc80d1bbfe,Industriell verksamhetsutvecklare inom IT och ...,Jobnet AB,Göteborg,Västra Götalands län,"Affärskonsult, IT",2025-01-22T17:38:54,2025-03-26T23:59:59,"Bli en del av Prevas, ett innovativt företag i..."
3,29403435,9e26031d28b6d5255204909d767f11d367f90a48,Industriell verksamhetsutvecklare inom IT och ...,Jobnet AB,Göteborg,Västra Götalands län,"Affärskonsult, IT",2025-01-22T17:38:54,2025-04-02T23:59:59,"Bli en del av Prevas, ett innovativt företag i..."
4,29403435,5e5363fbd7ed8ab6f5a52b7e1bd40f8a0f1b92de,Industriell verksamhetsutvecklare inom IT och ...,Jobnet AB,Göteborg,Västra Götalands län,"Affärskonsult, IT",2025-01-22T17:38:54,2025-04-09T23:59:59,"Bli en del av Prevas, ett innovativt företag i..."

In [ ]:
with open("../data/skills_2511.json", encoding="utf-8") as f:
    tax = pd.DataFrame(json.load(f))

tax.head()

,skill_id,skill,headlines
0,13ad_dCC_Tn6,"OOS, styr- och utvecklingsmodell",[Styr- och utvecklingsmodeller]
1,16ZN_3Zp_bYV,"Odoo, molnplattform",[Applikationsplattformar]
2,19PK_uxU_Wzy,"Bower, pakethanterare",[Programmerings- och systemutvecklingsverktyg]
3,1CmG_8hR_igc,Bluetooth-teknik,[Kommunikationsprotokoll]
4,1QYQ_Xka_TQ5,"Microsoft Autopilot, systemutvecklingsverktyg",[Programmerings- och systemutvecklingsverktyg]